# Generated by Django 4.0.4 on 2022-05-22 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP',
            new_name='SetOtp',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'.", regex='^\\+?234?\\d{9,17}$')]),
        ),
    ]
