# Generated by Django 4.0.4 on 2022-05-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('bank_name', models.CharField(choices=[('Select', 'select'), ('Zenith Bank', 'zenith bank'), ('GT Bank', 'gt bank'), ('Eco Bank', 'eco bank'), ('UBA Bank', 'uba bank'), ('Polaris Bank', 'polaris bank'), ('Standard Chartered Bank', 'standard chartered bank'), ('Keystone Bank', 'keystone bank'), ('Access Bank', 'access bank'), ('Sterling Bank', 'sterling bank')], default='Select', max_length=50)),
                ('token', models.CharField(choices=[('Select', 'select'), ('NFT', 'nft'), ('Cryptocurrency', 'cryptocurrency'), ('All', 'all'), ('Cash', 'cash')], default='Select', max_length=50)),
                ('cash_avaliable', models.FloatField()),
                ('token_avaliable', models.FloatField()),
            ],
            options={
                'verbose_name': "User's Account",
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_token', models.CharField(blank=True, choices=[('Cryptocurrency', 'cryptocurrency'), ('NFT', 'nft'), ('None', 'none')], max_length=50, null=True)),
                ('cash_amount', models.FloatField(blank=True, null=True)),
                ('token_amount', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
            options={
                'verbose_name': 'Withdraw',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_token', models.CharField(blank=True, choices=[('Cryptocurrency', 'cryptocurrency'), ('NFT', 'nft'), ('None', 'none')], max_length=50, null=True)),
                ('cash_amount', models.FloatField(blank=True, null=True)),
                ('token_amount', models.FloatField(blank=True, null=True)),
                ('account_no_transferred', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
            options={
                'verbose_name': 'Transfer',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
            options={
                'verbose_name': 'Deposit',
            },
        ),
        migrations.CreateModel(
            name='check_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
            options={
                'verbose_name': 'Check Balance',
            },
        ),
    ]
