# Generated by Django 4.0.4 on 2022-05-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_cash_avaliable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='bank_name',
            field=models.CharField(choices=[('Select', 'select'), ('Zenith Bank', 'zenith bank'), ('GT Bank', 'gt bank'), ('Eco Bank', 'eco bank'), ('UBA Bank', 'uba bank'), ('Polaris Bank', 'polaris bank'), ('Standard Chartered Bank', 'standard chartered bank'), ('Keystone Bank', 'keystone bank'), ('Access Bank', 'access bank'), ('Sterling Bank', 'sterling bank')], default='select', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(choices=[('Select', 'select'), ('Zenith Bank', 'zenith bank'), ('GT Bank', 'gt bank'), ('Eco Bank', 'eco bank'), ('UBA Bank', 'uba bank'), ('Polaris Bank', 'polaris bank'), ('Standard Chartered Bank', 'standard chartered bank'), ('Keystone Bank', 'keystone bank'), ('Access Bank', 'access bank'), ('Sterling Bank', 'sterling bank')], default='select', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(choices=[('Select', 'select'), ('NFT', 'nft'), ('Cryptocurrency', 'cryptocurrency'), ('All', 'all'), ('Cash', 'cash')], default='select', max_length=50),
        ),
    ]
